### ISSUE TITLE
Homekit cannot connect to this accessory

### ISSUE THREAD

**Issue by noahmaes** [paresy/HomeKit#79]
Thank you for this piece of software;

Can you please have a look at the following;
1. I added the 'homekit bridge' to Symcom
2. I added a switch in the 'homekit bridge' in Symcon
3. The Symcon is visable in my homekit app, I can submit the "setup code"

Aftern submitting the "setup code " it takes >5 minutes adding the Symcon, resulting in a timeout: Homekit cannot connect to this accessory.

**Comment by noahmaes** [comment]
![IMG_2553](https://user-images.githubusercontent.com/49767996/56980953-fd85d000-6b7d-11e9-81f8-29e6902e882b.png)
![IMG_2552](https://user-images.githubusercontent.com/49767996/56980954-fd85d000-6b7d-11e9-9cf8-4bf8f0290b30.png)

**Comment by paresy** [comment]
Unfortunately i cannot reproduce this issue? Is it still happening? Which IP-Symcon version on which platform are you using?

**Comment by ejjoman** [comment]
I had the same problem.
IP-Symcon running in Docker on a Ubuntu 20.04 server host.

Symcon is visible in Homekit app, but could not connect to the server (same error shown in OPs post). No debug entries were written while trying to connect from the Homekit app.
To exlude network/firewall related problems, I connected via telnet to the defined port (here: 34587) from different machines (localhost, other PCs) which worked great.
The connections were even visible in the debug windows of the Homekit Bridge module and the Server Socket.

The solution for me was to add the FQDN to the DNS-SD entry (e.g. "server1.example.com" or "server1.local", check your network configuration for that).
This is the only way I could get the Homekit app to work with the IP-Symcon Homekit Bridge.

The problem: The hostname is always removed from the DNS-SD entry as soon as I change anything in the Bridge's config.
You even need to re-enter the hostname a bunch of times while the app tries to connect, because it gets removed multiple times during this step.

Would it be possible to not override custom DNS-SD settings every time the config changes?
